const state = { sessionId: localStorage.getItem('research-os-session') || null, jobId: null, response: null, tab: 'current' };
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const pretty = (value) => typeof value === 'string' ? value : JSON.stringify(value, null, 2);
const safeUrl = (value) => /^https?:\/\//i.test(String(value || '')) ? esc(value) : '#';

async function request(path, options = {}) {
  const response = await fetch(path, {headers: {'Content-Type': 'application/json'}, ...options});
  const payload = await response.json();
  if (!response.ok) throw new Error(payload.error?.message || 'Request failed');
  return payload;
}

function addMessage(role, content, meta = '') {
  const chat = $('#chat');
  const welcome = chat.querySelector('.welcome');
  if (welcome) welcome.remove();
  const item = document.createElement('div');
  item.className = `message ${role}`;
  item.innerHTML = `<div class="avatar">${role === 'user' ? '↗' : '◈'}</div><div><div class="message-body">${esc(content)}</div>${meta ? `<div class="message-meta">${esc(meta)}</div>` : ''}</div>`;
  chat.appendChild(item); chat.scrollTop = chat.scrollHeight;
}

function setStatus(status) { const pill = $('#status-pill'); pill.textContent = status; pill.className = `status-pill ${status === 'COMPLETED' || status === 'SUPPORTED' ? 'good' : status === 'INDETERMINATE' || status === 'INSUFFICIENT_EVIDENCE' ? 'warn' : status === 'FAILED' || status === 'REJECTED' ? 'bad' : ''}`; }

function renderCurrent() {
  const response = state.response; if (!response) { $('#inspector-content').innerHTML = '<div class="trace-empty">Your research plan, execution and evidence will appear here.</div>'; return; }
  const job = response.job, planning = response.planning, answer = response.answer, execution = response.execution;
  const trace = answer.metadata?.oracle_trace || {};
  $('#inspector-content').innerHTML = `<div class="trace-section"><div class="trace-title">RESEARCH STATUS</div><div class="trace-value">${esc(answer.status)}<br><span class="muted">${esc(answer.summary)}</span></div></div><div class="trace-section"><div class="trace-title">PROGRESS</div>${(job.progress || []).map(item => `<div class="progress-row ${item.completed ? 'done' : ''}"><span class="progress-icon">${item.completed ? '✓' : '○'}</span><span>${esc(item.message)}</span></div>`).join('')}</div><div class="trace-section"><div class="trace-title">QUESTION</div><div class="card">${esc(planning.question.objective)}</div></div>${answer.first_loss ? `<div class="trace-section"><div class="trace-title danger">FIRST_LOSS</div><div class="card danger"><strong>${esc(answer.first_loss.rule_id)}</strong><br>${esc(answer.first_loss.message || '')}</div></div>` : ''}<div class="trace-section"><div class="trace-title">ORACLE AUDIT</div><div class="kv"><label>Provider / mode</label><span>${esc(answer.metadata?.provider || '—')} · ${esc(answer.metadata?.provider_metadata?.mode || '—')}</span></div><div class="kv"><label>Plan / validation</label><span>${esc(trace.plan_id || planning.plan.plan_id)} · ${esc(trace.validation || planning.validation.status)}</span></div><div class="kv"><label>Repairs</label><span>${esc(trace.repair_count ?? planning.validation.repairs ?? 0)}</span></div><div class="kv"><label>Request digest</label><span>${esc((trace.request_digests || [])[0] || '—')}</span></div><div class="kv"><label>Response digest</label><span>${esc((trace.response_digests || [])[0] || '—')}</span></div><div class="kv"><label>Grounded</label><span>${answer.metadata?.grounded ? 'yes' : 'planning only'}</span></div></div>`;
}

function renderTab() {
  const response = state.response; if (!response) return renderCurrent();
  const {planning, answer, execution} = response; let html = '';
  if (state.tab === 'current') return renderCurrent();
  if (state.tab === 'plan') html = `<div class="trace-title">RESEARCH PLAN ${esc(planning.plan.plan_id)}</div>${(planning.plan.steps || []).map((step, index) => `<details class="step"><summary>${index + 1}. ${esc(step.lab)} <span class="badge">${esc(step.minimum_evidence_level)}</span></summary><div class="step-meta">${esc(step.experiment)} · requires ${esc((step.requires || []).join(', ') || 'none')}</div><div class="card"><strong>Inputs</strong><pre>${esc(pretty(step.inputs))}</pre></div></details>`).join('')}`;
  if (state.tab === 'result') html = `<div class="trace-section"><div class="trace-title">STATUS</div><div class="trace-value">${esc(answer.status)}</div></div><div class="card">${esc(answer.summary)}</div><div class="trace-title">CLAIMS</div>${(answer.claims || []).map(item => `<div class="card">✓ ${esc(item.statement || item.claim_id || item)}</div>`).join('') || '<div class="card muted">No claim was asserted beyond the recorded evidence.</div>'}<div class="trace-title">LIMITATIONS</div>${(answer.limitations || []).map(item => `<div class="card muted">${esc(item)}</div>`).join('') || '<div class="muted">No additional limitations recorded.</div>'}${answer.metadata?.research_gap ? `<div class="trace-title warning">RESEARCH GAP</div><div class="card warning"><strong>Required: ${esc(answer.metadata.research_gap.required_evidence)}</strong><br>${esc(answer.metadata.research_gap.missing_information.join('; '))}</div>` : ''}`;
  if (state.tab === 'evidence') html = (answer.evidence || []).map(item => `<div class="card"><strong>${esc(item.evidence_id)}</strong><div class="kv"><label>Level</label><span>${esc(item.level)}</span></div><div class="kv"><label>Kind</label><span>${esc(item.kind)}</span></div><div class="kv"><label>Source</label><span>${esc(item.source)}</span></div><div class="kv"><label>Run</label><span>${esc(item.run_id)}</span></div><div class="kv"><label>Limitations</label><span>${esc((item.limitations || []).join('; '))}</span></div></div>`).join('') || '<div class="trace-empty">No Evidence was produced.</div>';
  if (state.tab === 'sources') html = `<div id="source-cards">${(answer.sources || []).map(source => `<div class="card"><strong>${esc(source.source_id || source)}</strong><br>${esc(source.title || 'Citation record')}<br><span class="muted">${esc(source.url || source.locator || '')}</span></div>`).join('') || '<div class="trace-empty">No reviewed source matched this question.</div>'}</div>`;
  if (state.tab === 'runs') html = (execution?.runs ? Object.entries(execution.runs).map(([step, run]) => `<div class="card"><strong>${esc(run.run_id || step)}</strong><br>${esc(run.lab || step)} · ${esc(run.status || '')}<br><span class="muted">${esc(run.experiment || '')}</span></div>`).join('') : (answer.run_ids || []).map(run => `<div class="card">${esc(run)}</div>`).join('')) || '<div class="trace-empty">No persisted runs in this response.</div>';
  if (state.tab === 'lineage') html = `<div class="card"><strong>Workflow</strong><br>${esc(answer.workflow_ids?.join(', ') || '—')}</div><div class="card"><strong>Rerun of</strong><br>${esc(planning.plan.rerun_of || 'original workflow')}</div><div class="card"><strong>Runs</strong><br>${esc((answer.run_ids || []).join(' → ') || '—')}</div>${answer.first_divergence ? `<div class="card warning"><strong>FIRST_DIVERGENCE</strong><br>${esc(answer.first_divergence.step_id)} · ${esc(answer.first_divergence.reason)}</div>` : ''}`;
  if (state.tab === 'review') html = '<div class="trace-empty">Knowledge review queue is available from the source workspace. Imported material remains REVIEW_REQUIRED until a human verifies it.</div><button class="reference" onclick="loadReview()">Refresh review queue</button><div id="review-list"></div>';
  $('#inspector-content').innerHTML = html;
  if (state.tab === 'review') loadReview();
  if (state.tab === 'sources' && state.jobId) loadSources();
}

async function loadSources() { try { const data = await request(`/api/jobs/${state.jobId}/sources`); const target = $('#source-cards'); if (!target) return; target.innerHTML = data.sources.map(source => `<div class="card"><strong>${esc(source.source_id)}</strong><br>${esc(source.title || 'Citation record')}<div class="kv"><label>Authors</label><span>${esc((source.authors || []).join(', ') || '—')}</span></div><div class="kv"><label>Year / DOI</label><span>${esc(source.year || '—')} · ${esc(source.doi || '—')}</span></div><div class="kv"><label>Type / License</label><span>${esc(source.source_type || '—')} · ${esc(source.license || '—')}</span></div><a class="source-link" href="${safeUrl(source.url)}" target="_blank" rel="noreferrer">Open source ↗</a></div>`).join('') || '<div class="trace-empty">No reviewed source matched this question.</div>'; } catch (_) {} }

async function submit(message) {
  addMessage('user', message); $('#message').value = ''; setStatus('RUNNING');
  try { const payload = await request('/api/chat', {method: 'POST', body: JSON.stringify({message, session_id: state.sessionId})}); state.sessionId = payload.session_id; localStorage.setItem('research-os-session', state.sessionId); state.jobId = payload.response.job.job_id; state.response = payload.response; $('#session-title').textContent = payload.response.planning.question.objective; $('#continue').disabled = false; addMessage('oracle', payload.response.answer.summary, payload.response.answer.status); setStatus(payload.response.answer.status); renderTab(); loadHistory(); } catch (error) { addMessage('oracle', `I could not complete this request: ${error.message}`, 'ERROR'); setStatus('FAILED'); }
}

async function loadHistory() { try { const data = await request('/api/sessions'); $('#history').innerHTML = data.sessions.map(session => `<button class="history-item ${session.session_id === state.sessionId ? 'active' : ''}" data-session="${esc(session.session_id)}"><strong>${esc(session.title)}</strong><small>${esc(session.status)} · ${new Date(session.updated_at).toLocaleString()}</small></button>`).join('') || '<div class="empty">No saved research yet.</div>'; document.querySelectorAll('[data-session]').forEach(button => button.onclick = () => openSession(button.dataset.session)); } catch (_) {} }
async function openSession(sessionId) { state.sessionId = sessionId; localStorage.setItem('research-os-session', sessionId); const session = await request(`/api/sessions/${encodeURIComponent(sessionId)}`); $('#session-title').textContent = session.title; $('#chat').innerHTML = ''; [...(session.user_messages || []), ...(session.oracle_messages || [])].sort((a,b) => a.timestamp.localeCompare(b.timestamp)).forEach(item => addMessage(item.role === 'user' ? 'user' : 'oracle', item.content)); const jobs = await request(`/api/sessions/${encodeURIComponent(sessionId)}/jobs`); if (jobs.jobs?.length) { const latest = jobs.jobs[0]; state.jobId = latest.job_id; state.response = await request(`/api/jobs/${latest.job_id}`); $('#continue').disabled = false; setStatus(state.response.answer.status); renderTab(); } loadHistory(); }
async function loadOracleStatus() { try { const data = await request('/api/oracle/audit'); $('#oracle-status').innerHTML = `<div class="system-status-title">${esc(data.oracle_llm)} · ${esc(data.mode)}</div><div class="kv"><label>Live validation</label><span>${esc(data.live_oracle_validation)}</span></div><div class="kv"><label>Evidence provider</label><span>${data.scientific_evidence_provider ? 'yes' : 'NO'}</span></div><div class="kv"><label>Planner / narrator</label><span>${esc(data.planner)} / ${esc(data.narrator)}</span></div><div class="kv"><label>Standalone web LLM</label><span>${esc(data.standalone_web_llm)}</span></div><div class="kv"><label>Validation / grounding</label><span>${esc(data.plan_validator)} / ${esc(data.grounding)}</span></div>`; } catch (_) {} }
async function loadEngines() { const data = await request('/api/engines'); $('#engines').innerHTML = data.engines.map(engine => `<div class="engine"><div><div class="engine-name">${esc(engine.name)}</div><div class="engine-state">${esc(engine.status)} · ${esc(engine.version || 'no version')}</div></div><div class="badge">${engine.available ? 'AVAILABLE' : engine.status}</div><div class="engine-flags"><span class="badge">configured: ${engine.configured}</span><span class="badge">executed: ${engine.executed}</span><span class="badge">reference: ${engine.reference_validated}</span></div></div>`).join(''); }
async function loadReview() { try { const data = await request('/api/knowledge/review-queue'); const target = $('#review-list'); if (target) target.innerHTML = data.items.map(item => `<div class="card"><strong>${esc(item.item_type)}</strong> · ${esc(item.item_id)}<br><span class="muted">${esc(item.reason)}</span><br><button class="reference" onclick="review('${esc(item.review_id)}','VERIFY')">Verify</button> <button class="quiet" onclick="review('${esc(item.review_id)}','REJECT')">Reject</button></div>`).join('') || `<div class="trace-empty">${esc(data.status)}</div>`; } catch (_) {} }
async function review(id, status) { await request(`/api/knowledge/review/${id}`, {method:'POST', body: JSON.stringify({status})}); loadReview(); }

$('#composer').onsubmit = (event) => { event.preventDefault(); const value = $('#message').value.trim(); if (value) submit(value); };
$('#message').onkeydown = (event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); $('#composer').requestSubmit(); } };
document.querySelectorAll('[data-example]').forEach(button => button.onclick = () => submit(button.dataset.example));
document.querySelectorAll('[data-tab]').forEach(button => button.onclick = () => { document.querySelectorAll('.tab').forEach(item => item.classList.remove('active')); button.classList.add('active'); state.tab = button.dataset.tab; renderTab(); });
$('#new-session').onclick = async () => { const data = await request('/api/sessions', {method:'POST', body: JSON.stringify({title:'New research'})}); state.sessionId = data.session_id; localStorage.setItem('research-os-session', state.sessionId); state.response = null; state.jobId = null; $('#chat').innerHTML = '<div class="welcome"><div class="welcome-orb">◈</div><h2>Ask the Oracle</h2><p>Describe the question in your own words.</p></div>'; $('#session-title').textContent = 'What do you want to research?'; $('#continue').disabled = true; setStatus('IDLE'); renderCurrent(); loadHistory(); };
$('#continue').onclick = async () => { if (!state.jobId) return; const payload = await request(`/api/jobs/${state.jobId}/continue`, {method:'POST', body:'{}'}); state.jobId = payload.response.job.job_id; state.response = payload.response; addMessage('oracle', payload.response.answer.summary, 'CONTINUATION'); setStatus(payload.response.answer.status); renderTab(); loadHistory(); };
$('#engine-button').onclick = () => { $('#engine-dialog').showModal(); loadOracleStatus(); loadEngines(); }; $('#close-engine').onclick = () => $('#engine-dialog').close(); $('#reference').onclick = async () => { await request('/api/engines/reference', {method:'POST',body:'{}'}); loadEngines(); };
loadOracleStatus(); loadHistory(); if (state.sessionId) openSession(state.sessionId).catch(() => { localStorage.removeItem('research-os-session'); state.sessionId = null; });
